//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace BitSite {
    
    
    public partial class EditPage {
        
        /// <summary>
        /// BitStyleScriptadc4059d33834066b1b79488798f6a87 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlLink BitStyleScriptadc4059d33834066b1b79488798f6a87;
        
        /// <summary>
        /// BitStyleScript3bcb150267724dd4b1c7343da40aeb32 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlLink BitStyleScript3bcb150267724dd4b1c7343da40aeb32;
        
        /// <summary>
        /// BitStyleScript67bd67cfd77f48cb824c901b44e8b29e control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlLink BitStyleScript67bd67cfd77f48cb824c901b44e8b29e;
        
        /// <summary>
        /// EditPageMenu2 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::BitSite._bitPlate.EditPage.EditPageMenu2 EditPageMenu2;
    }
}
