//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BitMetaServer20.BitplateBackupServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://bitnetmedia.bitplate.backup", ConfigurationName="BitplateBackupServiceReference.IBackupService")]
    public interface IBackupService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://bitnetmedia.bitplate.backup/IBackupService/MakeBackup", ReplyAction="http://bitnetmedia.bitplate.backup/IBackupService/MakeBackupResponse")]
        bool MakeBackup(System.Guid siteId, string filePath, string databaseConnectionString);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://bitnetmedia.bitplate.backup/IBackupService/GetBackupStatus", ReplyAction="http://bitnetmedia.bitplate.backup/IBackupService/GetBackupStatusResponse")]
        string GetBackupStatus(System.Guid siteId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://bitnetmedia.bitplate.backup/IBackupService/RestoreBackup", ReplyAction="http://bitnetmedia.bitplate.backup/IBackupService/RestoreBackupResponse")]
        bool RestoreBackup(System.Guid siteId, string filePath, string backupName, string databaseConnectionString);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IBackupServiceChannel : BitMetaServer20.BitplateBackupServiceReference.IBackupService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BackupServiceClient : System.ServiceModel.ClientBase<BitMetaServer20.BitplateBackupServiceReference.IBackupService>, BitMetaServer20.BitplateBackupServiceReference.IBackupService {
        
        public BackupServiceClient() {
        }
        
        public BackupServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public BackupServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BackupServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BackupServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool MakeBackup(System.Guid siteId, string filePath, string databaseConnectionString) {
            return base.Channel.MakeBackup(siteId, filePath, databaseConnectionString);
        }
        
        public string GetBackupStatus(System.Guid siteId) {
            return base.Channel.GetBackupStatus(siteId);
        }
        
        public bool RestoreBackup(System.Guid siteId, string filePath, string backupName, string databaseConnectionString) {
            return base.Channel.RestoreBackup(siteId, filePath, backupName, databaseConnectionString);
        }
    }
}
