
SET FOREIGN_KEY_CHECKS=0;
SET UNIQUE_CHECKS=0;

-- -----------------------------------------------------
-- Table backup
-- -----------------------------------------------------
CREATE  TABLE IF NOT EXISTS backup (
  ID VARCHAR(36) NOT NULL ,
  Name VARCHAR(50) NULL DEFAULT NULL ,
  CreateDate DATETIME NULL DEFAULT NULL ,
  ModifiedDate DATETIME NULL DEFAULT NULL ,
  DateFrom DATETIME NULL DEFAULT NULL ,
  DateTill DATETIME NULL DEFAULT NULL ,
  FK_Site VARCHAR(36) NULL DEFAULT NULL ,
  BitPlateVersion VARCHAR(10) NULL DEFAULT NULL ,
  Path VARCHAR(100) NULL DEFAULT NULL ,
  UserName VARCHAR(50) NULL DEFAULT NULL ,
  Sites VARCHAR(1000) NULL DEFAULT NULL ,
  Active INT(11) NULL DEFAULT NULL ,
  INDEX FK_Site_Index (FK_Site ASC) )
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table bitplateuser
-- -----------------------------------------------------
CREATE  TABLE IF NOT EXISTS bitplateuser (
  ID VARCHAR(36) NOT NULL ,
  Name VARCHAR(50) NULL DEFAULT NULL ,
  CreateDate DATETIME NULL DEFAULT NULL ,
  ModifiedDate DATETIME NULL DEFAULT NULL ,
  DateFrom DATETIME NULL DEFAULT NULL ,
  DateTill DATETIME NULL DEFAULT NULL ,
  FK_Site VARCHAR(36) NULL DEFAULT NULL ,
  Password VARCHAR(100) NULL DEFAULT NULL ,
  Email VARCHAR(50) NULL DEFAULT NULL ,
  Telephone VARCHAR(50) NULL DEFAULT NULL ,
  Gender INT(11) NULL DEFAULT NULL ,
  MessageHeader VARCHAR(50) NULL DEFAULT NULL ,
  BirthDate DATETIME NULL DEFAULT NULL ,
  Address VARCHAR(50) NULL DEFAULT NULL ,
  Postalcode VARCHAR(50) NULL DEFAULT NULL ,
  City VARCHAR(50) NULL DEFAULT NULL ,
  Country VARCHAR(50) NULL DEFAULT NULL ,
  IsSystemValue BIT(1) NULL DEFAULT NULL ,
  IPAddress VARCHAR(20) CHARACTER SET 'utf8' NULL DEFAULT NULL ,
  AllowLogin BIT(1) NULL DEFAULT NULL ,
  EmailIsValid BIT(1) NULL DEFAULT NULL ,
  ReceiveNewsletter BIT(1) NULL DEFAULT NULL ,
  Registration VARCHAR(50) CHARACTER SET 'utf8' NULL DEFAULT NULL ,
  SecretCode VARCHAR(100) CHARACTER SET 'utf8' NULL DEFAULT NULL ,
  CustomerNumber VARCHAR(50) NULL DEFAULT NULL ,
  CompanyName VARCHAR(150) NULL DEFAULT NULL ,
  FaxNumber VARCHAR(50) NULL DEFAULT NULL ,
  AcceptConditions BIT(1) NULL DEFAULT NULL ,
  DateUnsubscribed DATETIME NULL DEFAULT NULL ,
  ForeName VARCHAR(250) NULL DEFAULT NULL ,
  NamePrefix VARCHAR(25) NULL DEFAULT NULL ,
  FormData TEXT NULL DEFAULT NULL ,
  Active INT(11) NULL DEFAULT NULL ,
  PasswordLastChanged DATETIME NULL DEFAULT NULL ,
  permissions VARCHAR(2000) NULL DEFAULT NULL ,
  Language VARCHAR(10) NULL DEFAULT NULL ,
  Theme VARCHAR(50) NULL DEFAULT NULL ,
  IsMultiSiteUser BIT(1) NULL DEFAULT NULL ,
  SiteUrls VARCHAR(2000) NULL DEFAULT NULL ,
  PRIMARY KEY (ID) ,
  UNIQUE INDEX EmailPerSiteUnique (Email ASC, FK_Site ASC) ,
  INDEX FK_Site_Index (FK_Site ASC) )
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table bitplateusergroup
-- -----------------------------------------------------
CREATE  TABLE IF NOT EXISTS bitplateusergroup (
  ID VARCHAR(36) NOT NULL ,
  Name VARCHAR(50) NULL DEFAULT NULL ,
  CreateDate DATETIME NULL DEFAULT NULL ,
  ModifiedDate DATETIME NULL DEFAULT NULL ,
  DateFrom DATETIME NULL DEFAULT NULL ,
  DateTill DATETIME NULL DEFAULT NULL ,
  FK_Site VARCHAR(36) NULL DEFAULT NULL ,
  Type INT(11) NULL DEFAULT NULL ,
  IsPublicVisible BIT(1) NULL DEFAULT NULL ,
  FK_Parent_Group VARCHAR(36) NULL DEFAULT NULL ,
  Active INT(11) NULL DEFAULT NULL ,
  permissions VARCHAR(2000) NULL DEFAULT NULL ,
  IsSystemValue BIT(1) NULL DEFAULT NULL ,
  PRIMARY KEY (ID) ,
  INDEX FK_Site_Index (FK_Site ASC) ,
  INDEX usergroup_parent_group (FK_Parent_Group ASC) )
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table bitplateusergroupperuser
-- -----------------------------------------------------
CREATE  TABLE IF NOT EXISTS bitplateusergroupperuser (
  ID VARCHAR(36) NOT NULL ,
  Name VARCHAR(50) NULL DEFAULT NULL ,
  CreateDate DATETIME NULL DEFAULT NULL ,
  ModifiedDate DATETIME NULL DEFAULT NULL ,
  DateFrom DATETIME NULL DEFAULT NULL ,
  DateTill DATETIME NULL DEFAULT NULL ,
  FK_Site VARCHAR(36) NULL DEFAULT NULL ,
  FK_User VARCHAR(36) NULL DEFAULT NULL ,
  FK_UserGroup VARCHAR(36) NULL DEFAULT NULL ,
  Active INT(11) NULL DEFAULT NULL ,
  PRIMARY KEY (ID) ,
  INDEX FK_Site_Index (FK_Site ASC) ,
  INDEX FK_User_Index (FK_User ASC) ,
  INDEX FK_UserGroup_Index (FK_UserGroup ASC) )
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table datacollection
-- -----------------------------------------------------
CREATE  TABLE IF NOT EXISTS datacollection (
  ID VARCHAR(36) NOT NULL ,
  Name VARCHAR(50) NULL DEFAULT NULL ,
  CreateDate DATETIME NULL DEFAULT NULL ,
  ModifiedDate DATETIME NULL DEFAULT NULL ,
  DateFrom DATETIME NULL DEFAULT NULL ,
  DateTill DATETIME NULL DEFAULT NULL ,
  FK_Site VARCHAR(36) NULL DEFAULT NULL ,
  Type INT(11) NULL DEFAULT NULL ,
  Active INT(11) NULL DEFAULT NULL ,
  HasAutorisation BIT(1) NULL DEFAULT NULL ,
  ChangeStatus INT(11) NULL DEFAULT NULL ,
  LastPublishedDate DATETIME NULL DEFAULT NULL ,
  LanguageCode VARCHAR(2) NULL DEFAULT NULL ,
  PRIMARY KEY (ID) ,
  UNIQUE INDEX datacollectionNameUnique (FK_Site ASC, Name ASC) )
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table datafield
-- -----------------------------------------------------
CREATE  TABLE IF NOT EXISTS datafield (
  ID VARCHAR(36) NOT NULL ,
  Name VARCHAR(50) NULL DEFAULT NULL ,
  CreateDate DATETIME NULL DEFAULT NULL ,
  ModifiedDate DATETIME NULL DEFAULT NULL ,
  DateFrom DATETIME NULL DEFAULT NULL ,
  DateTill DATETIME NULL DEFAULT NULL ,
  Active INT(11) NULL DEFAULT NULL ,
  FK_Site VARCHAR(36) NULL DEFAULT NULL ,
  FK_DataCollection VARCHAR(36) NULL DEFAULT NULL ,
  Type VARCHAR(10) NULL DEFAULT NULL ,
  FieldType INT(11) NULL DEFAULT NULL ,
  MappingColumn VARCHAR(100) NULL DEFAULT NULL ,
  IsMultiLanguageField BIT(1) NULL DEFAULT NULL ,
  OrderingNumber INT(11) NULL DEFAULT NULL ,
  TabPage VARCHAR(50) NULL DEFAULT NULL ,
  IsSystemField BIT(1) NULL DEFAULT NULL ,
  DefaultValue VARCHAR(255) NULL DEFAULT NULL ,
  FieldRule INT(11) NULL DEFAULT '0' ,
  PRIMARY KEY (ID) ,
  UNIQUE INDEX datafieldNameUnique (Name ASC, Type ASC, FK_DataCollection ASC) ,
  INDEX FK_Site_Index (FK_Site ASC) ,
  INDEX FK_DataCollection_Index (FK_DataCollection ASC) )
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table datafile
-- -----------------------------------------------------
CREATE  TABLE IF NOT EXISTS datafile (
  ID VARCHAR(36) NOT NULL ,
  Name VARCHAR(50) NULL DEFAULT NULL ,
  CreateDate DATETIME NULL DEFAULT NULL ,
  ModifiedDate DATETIME NULL DEFAULT NULL ,
  DateFrom DATETIME NULL DEFAULT NULL ,
  DateTill DATETIME NULL DEFAULT NULL ,
  FK_Site VARCHAR(36) NULL DEFAULT NULL ,
  FK_Item VARCHAR(36) NULL DEFAULT NULL ,
  FK_Group VARCHAR(36) NULL DEFAULT NULL ,
  Url VARCHAR(255) NULL DEFAULT NULL ,
  Language VARCHAR(50) NULL DEFAULT NULL ,
  Type VARCHAR(15) NULL DEFAULT NULL ,
  Active INT(11) NULL DEFAULT NULL ,
  PRIMARY KEY (ID) ,
  INDEX FK_Site (FK_Site ASC) ,
  INDEX FK_Item (FK_Item ASC) ,
  INDEX FK_Group (FK_Group ASC) )
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table datagroup
-- -----------------------------------------------------
CREATE  TABLE IF NOT EXISTS datagroup (
  ID VARCHAR(36) NOT NULL ,
  Name VARCHAR(50) NULL DEFAULT NULL ,
  CreateDate DATETIME NULL DEFAULT NULL ,
  ModifiedDate DATETIME NULL DEFAULT NULL ,
  DateFrom DATETIME NULL DEFAULT NULL ,
  DateTill DATETIME NULL DEFAULT NULL ,
  FK_Site VARCHAR(36) NULL DEFAULT NULL ,
  FK_DataCollection VARCHAR(36) NULL DEFAULT NULL ,
  FK_Parent_Group VARCHAR(36) NULL DEFAULT NULL ,
  Title VARCHAR(250) NULL DEFAULT NULL ,
  CompletePath VARCHAR(255) NULL DEFAULT NULL ,
  Active INT(11) NULL DEFAULT NULL ,
  ChangeStatus INT(11) NULL DEFAULT NULL ,
  LastPublishedDate DATETIME NULL DEFAULT NULL ,
  LastPublishedFileName VARCHAR(500) NULL DEFAULT NULL ,
  Text1 VARCHAR(255) NULL DEFAULT NULL ,
  Text2 VARCHAR(255) NULL DEFAULT NULL ,
  Text3 VARCHAR(255) NULL DEFAULT NULL ,
  Text4 VARCHAR(255) NULL DEFAULT NULL ,
  Text5 VARCHAR(255) NULL DEFAULT NULL ,
  LongText1 TEXT NULL DEFAULT NULL ,
  Html1 TEXT NULL DEFAULT NULL ,
  numeric1 INT(11) NULL DEFAULT NULL ,
  Currency1 FLOAT NULL DEFAULT NULL ,
  DateTime1 DATETIME NULL DEFAULT NULL ,
  YesNo1 BIT(1) NULL DEFAULT NULL ,
  Image1 VARCHAR(255) NULL DEFAULT NULL ,
  Image2 VARCHAR(255) NULL DEFAULT NULL ,
  Image3 VARCHAR(255) NULL DEFAULT NULL ,
  Image4 VARCHAR(255) NULL DEFAULT NULL ,
  Image5 VARCHAR(255) NULL DEFAULT NULL ,
  File1 VARCHAR(255) NULL DEFAULT NULL ,
  FK_1 VARCHAR(36) NULL DEFAULT NULL ,
  FK_2 VARCHAR(36) NULL DEFAULT NULL ,
  FK_3 VARCHAR(36) NULL DEFAULT NULL ,
  FK_4 VARCHAR(36) NULL DEFAULT NULL ,
  FK_5 VARCHAR(36) NULL DEFAULT NULL ,
  FK_6 VARCHAR(36) NULL DEFAULT NULL ,
  FK_7 VARCHAR(36) NULL DEFAULT NULL ,
  FK_8 VARCHAR(36) NULL DEFAULT NULL ,
  FK_9 VARCHAR(36) NULL DEFAULT NULL ,
  FK_10 VARCHAR(36) NULL DEFAULT NULL ,
  HasAutorisation BIT(1) NULL DEFAULT NULL ,
  text6 VARCHAR(255) NULL DEFAULT NULL ,
  text7 VARCHAR(255) NULL DEFAULT NULL ,
  text8 VARCHAR(255) NULL DEFAULT NULL ,
  text9 VARCHAR(255) NULL DEFAULT NULL ,
  text10 VARCHAR(255) NULL DEFAULT NULL ,
  text11 VARCHAR(255) NULL DEFAULT NULL ,
  text12 VARCHAR(255) NULL DEFAULT NULL ,
  text13 VARCHAR(255) NULL DEFAULT NULL ,
  text14 VARCHAR(255) NULL DEFAULT NULL ,
  text15 VARCHAR(255) NULL DEFAULT NULL ,
  text16 VARCHAR(255) NULL DEFAULT NULL ,
  text17 VARCHAR(255) NULL DEFAULT NULL ,
  text18 VARCHAR(255) NULL DEFAULT NULL ,
  text19 VARCHAR(255) NULL DEFAULT NULL ,
  text20 VARCHAR(255) NULL DEFAULT NULL ,
  text21 VARCHAR(255) NULL DEFAULT NULL ,
  text22 VARCHAR(255) NULL DEFAULT NULL ,
  text23 VARCHAR(255) NULL DEFAULT NULL ,
  text24 VARCHAR(255) NULL DEFAULT NULL ,
  text25 VARCHAR(255) NULL DEFAULT NULL ,
  text26 VARCHAR(255) NULL DEFAULT NULL ,
  text27 VARCHAR(255) NULL DEFAULT NULL ,
  text28 VARCHAR(255) NULL DEFAULT NULL ,
  text29 VARCHAR(255) NULL DEFAULT NULL ,
  text30 VARCHAR(255) NULL DEFAULT NULL ,
  longtext2 TEXT NULL DEFAULT NULL ,
  longtext3 TEXT NULL DEFAULT NULL ,
  longtext4 TEXT NULL DEFAULT NULL ,
  longtext5 TEXT NULL DEFAULT NULL ,
  html2 TEXT NULL DEFAULT NULL ,
  html3 TEXT NULL DEFAULT NULL ,
  html4 TEXT NULL DEFAULT NULL ,
  html5 TEXT NULL DEFAULT NULL ,
  numeric2 INT(11) NULL DEFAULT NULL ,
  numeric3 INT(11) NULL DEFAULT NULL ,
  numeric4 INT(11) NULL DEFAULT NULL ,
  numeric5 INT(11) NULL DEFAULT NULL ,
  currency2 FLOAT NULL DEFAULT NULL ,
  currency3 FLOAT NULL DEFAULT NULL ,
  currency4 FLOAT NULL DEFAULT NULL ,
  currency5 FLOAT NULL DEFAULT NULL ,
  datetime2 DATETIME NULL DEFAULT NULL ,
  datetime3 DATETIME NULL DEFAULT NULL ,
  datetime4 DATETIME NULL DEFAULT NULL ,
  datetime5 DATETIME NULL DEFAULT NULL ,
  yesno2 BIT(1) NULL DEFAULT NULL ,
  yesno3 BIT(1) NULL DEFAULT NULL ,
  yesno4 BIT(1) NULL DEFAULT NULL ,
  yesno5 BIT(1) NULL DEFAULT NULL ,
  file2 VARCHAR(1000) NULL DEFAULT NULL ,
  file3 VARCHAR(1000) NULL DEFAULT NULL ,
  file4 VARCHAR(1000) NULL DEFAULT NULL ,
  file5 VARCHAR(1000) NULL DEFAULT NULL ,
  OrderNumber INT(11) NULL DEFAULT NULL ,
  MetaKeywords VARCHAR(500) NULL DEFAULT NULL ,
  MetaDescription VARCHAR(500) NULL DEFAULT NULL ,
  PRIMARY KEY (ID) ,
  UNIQUE INDEX groupUnique (FK_Parent_Group ASC, Name ASC) ,
  INDEX FK_Site_index (FK_Site ASC) ,
  INDEX FK_Parent_Group_index (FK_Parent_Group ASC) ,
  INDEX groupdata_fk_datacollection_index (FK_DataCollection ASC) ,
  INDEX groupdata_fk_parent_group (FK_Parent_Group ASC) ,
  INDEX FK_1 (FK_1 ASC) ,
  INDEX FK_2 (FK_2 ASC) ,
  INDEX FK_3 (FK_3 ASC) ,
  INDEX FK_4 (FK_4 ASC) ,
  INDEX FK_5 (FK_5 ASC) ,
  INDEX FK_6 (FK_6 ASC) ,
  INDEX FK_7 (FK_7 ASC) ,
  INDEX FK_8 (FK_8 ASC) ,
  INDEX FK_9 (FK_9 ASC) ,
  INDEX FK_10 (FK_10 ASC) )
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table datagrouplanguage
-- -----------------------------------------------------
CREATE  TABLE IF NOT EXISTS datagrouplanguage (
  ID VARCHAR(36) NOT NULL ,
  Name VARCHAR(150) NULL DEFAULT NULL ,
  CreateDate DATETIME NULL DEFAULT NULL ,
  ModifiedDate DATETIME NULL DEFAULT NULL ,
  DateFrom DATETIME NULL DEFAULT NULL ,
  DateTill DATETIME NULL DEFAULT NULL ,
  FK_Site VARCHAR(36) NULL DEFAULT NULL ,
  FK_DataCollection VARCHAR(36) NULL DEFAULT NULL ,
  FK_DataGroup VARCHAR(36) NULL DEFAULT NULL ,
  LanguageCode VARCHAR(5) NULL DEFAULT NULL ,
  Title VARCHAR(250) NULL DEFAULT NULL ,
  Active INT(11) NULL DEFAULT NULL ,
  ChangeStatus INT(11) NULL DEFAULT NULL ,
  LastPublishedDate DATETIME NULL DEFAULT NULL ,
  LastPublishedFileName VARCHAR(500) NULL DEFAULT NULL ,
  Text1 VARCHAR(255) NULL DEFAULT NULL ,
  Text2 VARCHAR(255) NULL DEFAULT NULL ,
  Text3 VARCHAR(255) NULL DEFAULT NULL ,
  Text4 VARCHAR(255) NULL DEFAULT NULL ,
  Text5 VARCHAR(255) NULL DEFAULT NULL ,
  LongText1 TEXT NULL DEFAULT NULL ,
  Html1 TEXT NULL DEFAULT NULL ,
  Image1 VARCHAR(255) NULL DEFAULT NULL ,
  Image2 VARCHAR(255) NULL DEFAULT NULL ,
  Image3 VARCHAR(255) NULL DEFAULT NULL ,
  Image4 VARCHAR(255) NULL DEFAULT NULL ,
  Image5 VARCHAR(255) NULL DEFAULT NULL ,
  File1 VARCHAR(255) NULL DEFAULT NULL ,
  FK_1 VARCHAR(36) NULL DEFAULT NULL ,
  FK_2 VARCHAR(36) NULL DEFAULT NULL ,
  FK_3 VARCHAR(36) NULL DEFAULT NULL ,
  FK_4 VARCHAR(36) NULL DEFAULT NULL ,
  FK_5 VARCHAR(36) NULL DEFAULT NULL ,
  FK_6 VARCHAR(36) NULL DEFAULT NULL ,
  FK_7 VARCHAR(36) NULL DEFAULT NULL ,
  FK_8 VARCHAR(36) NULL DEFAULT NULL ,
  FK_9 VARCHAR(36) NULL DEFAULT NULL ,
  FK_10 VARCHAR(36) NULL DEFAULT NULL ,
  HasAutorisation BIT(1) NULL DEFAULT NULL ,
  text6 VARCHAR(255) NULL DEFAULT NULL ,
  text7 VARCHAR(255) NULL DEFAULT NULL ,
  text8 VARCHAR(255) NULL DEFAULT NULL ,
  text9 VARCHAR(255) NULL DEFAULT NULL ,
  text10 VARCHAR(255) NULL DEFAULT NULL ,
  text11 VARCHAR(255) NULL DEFAULT NULL ,
  text12 VARCHAR(255) NULL DEFAULT NULL ,
  text13 VARCHAR(255) NULL DEFAULT NULL ,
  text14 VARCHAR(255) NULL DEFAULT NULL ,
  text15 VARCHAR(255) NULL DEFAULT NULL ,
  text16 VARCHAR(255) NULL DEFAULT NULL ,
  text17 VARCHAR(255) NULL DEFAULT NULL ,
  text18 VARCHAR(255) NULL DEFAULT NULL ,
  text19 VARCHAR(255) NULL DEFAULT NULL ,
  text20 VARCHAR(255) NULL DEFAULT NULL ,
  text21 VARCHAR(255) NULL DEFAULT NULL ,
  text22 VARCHAR(255) NULL DEFAULT NULL ,
  text23 VARCHAR(255) NULL DEFAULT NULL ,
  text24 VARCHAR(255) NULL DEFAULT NULL ,
  text25 VARCHAR(255) NULL DEFAULT NULL ,
  text26 VARCHAR(255) NULL DEFAULT NULL ,
  text27 VARCHAR(255) NULL DEFAULT NULL ,
  text28 VARCHAR(255) NULL DEFAULT NULL ,
  text29 VARCHAR(255) NULL DEFAULT NULL ,
  text30 VARCHAR(255) NULL DEFAULT NULL ,
  longtext2 TEXT NULL DEFAULT NULL ,
  longtext3 TEXT NULL DEFAULT NULL ,
  longtext4 TEXT NULL DEFAULT NULL ,
  longtext5 TEXT NULL DEFAULT NULL ,
  html2 TEXT NULL DEFAULT NULL ,
  html3 TEXT NULL DEFAULT NULL ,
  html4 TEXT NULL DEFAULT NULL ,
  html5 TEXT NULL DEFAULT NULL ,
  file2 VARCHAR(1000) NULL DEFAULT NULL ,
  file3 VARCHAR(1000) NULL DEFAULT NULL ,
  file4 VARCHAR(1000) NULL DEFAULT NULL ,
  file5 VARCHAR(1000) NULL DEFAULT NULL ,
  MetaKeywords VARCHAR(500) NULL DEFAULT NULL ,
  MetaDescription VARCHAR(500) NULL DEFAULT NULL ,
  PRIMARY KEY (ID) ,
  INDEX FK_Site (FK_Site ASC) ,
  INDEX FK_DataCollection (FK_DataCollection ASC) ,
  INDEX FK_DataGroup (FK_DataGroup ASC) ,
  INDEX DataItem_LanguageCode (LanguageCode ASC) )
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table dataitem
-- -----------------------------------------------------
CREATE  TABLE IF NOT EXISTS dataitem (
  ID VARCHAR(36) NOT NULL ,
  Name VARCHAR(150) NULL DEFAULT NULL ,
  CreateDate DATETIME NULL DEFAULT NULL ,
  ModifiedDate DATETIME NULL DEFAULT NULL ,
  DateFrom DATETIME NULL DEFAULT NULL ,
  DateTill DATETIME NULL DEFAULT NULL ,
  FK_Site VARCHAR(36) NULL DEFAULT NULL ,
  FK_DataCollection VARCHAR(36) NULL DEFAULT NULL ,
  FK_Parent_Group VARCHAR(36) NULL DEFAULT NULL ,
  Title VARCHAR(250) NULL DEFAULT NULL ,
  Address VARCHAR(50) NULL DEFAULT NULL ,
  PostalCode VARCHAR(50) NULL DEFAULT NULL ,
  Place VARCHAR(50) NULL DEFAULT NULL ,
  Country VARCHAR(50) NULL DEFAULT NULL ,
  Latitude FLOAT NULL DEFAULT NULL ,
  Longitude FLOAT NULL DEFAULT NULL ,
  CompletePath VARCHAR(255) NULL DEFAULT NULL ,
  Active INT(11) NULL DEFAULT NULL ,
  ChangeStatus INT(11) NULL DEFAULT NULL ,
  LastPublishedDate DATETIME NULL DEFAULT NULL ,
  Text1 VARCHAR(255) NULL DEFAULT NULL ,
  Text2 VARCHAR(255) NULL DEFAULT NULL ,
  Text3 VARCHAR(255) NULL DEFAULT NULL ,
  Text4 VARCHAR(255) NULL DEFAULT NULL ,
  Text5 VARCHAR(255) NULL DEFAULT NULL ,
  LongText1 TEXT NULL DEFAULT NULL ,
  Html1 TEXT NULL DEFAULT NULL ,
  numeric1 INT(11) NULL DEFAULT NULL ,
  Currency1 FLOAT NULL DEFAULT NULL ,
  DateTime1 DATETIME NULL DEFAULT NULL ,
  YesNo1 BIT(1) NULL DEFAULT NULL ,
  Image1 VARCHAR(255) NULL DEFAULT NULL ,
  Image2 VARCHAR(255) NULL DEFAULT NULL ,
  Image3 VARCHAR(255) NULL DEFAULT NULL ,
  Image4 VARCHAR(255) NULL DEFAULT NULL ,
  Image5 VARCHAR(255) NULL DEFAULT NULL ,
  File1 VARCHAR(255) NULL DEFAULT NULL ,
  FK_1 VARCHAR(36) NULL DEFAULT NULL ,
  FK_2 VARCHAR(36) NULL DEFAULT NULL ,
  FK_3 VARCHAR(36) NULL DEFAULT NULL ,
  FK_4 VARCHAR(36) NULL DEFAULT NULL ,
  FK_5 VARCHAR(36) NULL DEFAULT NULL ,
  FK_6 VARCHAR(36) NULL DEFAULT NULL ,
  FK_7 VARCHAR(36) NULL DEFAULT NULL ,
  FK_8 VARCHAR(36) NULL DEFAULT NULL ,
  FK_9 VARCHAR(36) NULL DEFAULT NULL ,
  FK_10 VARCHAR(36) NULL DEFAULT NULL ,
  HasAutorisation BIT(1) NULL DEFAULT NULL ,
  text6 VARCHAR(255) NULL DEFAULT NULL ,
  text7 VARCHAR(255) NULL DEFAULT NULL ,
  text8 VARCHAR(255) NULL DEFAULT NULL ,
  text9 VARCHAR(255) NULL DEFAULT NULL ,
  text10 VARCHAR(255) NULL DEFAULT NULL ,
  text11 VARCHAR(255) NULL DEFAULT NULL ,
  text12 VARCHAR(255) NULL DEFAULT NULL ,
  text13 VARCHAR(255) NULL DEFAULT NULL ,
  text14 VARCHAR(255) NULL DEFAULT NULL ,
  text15 VARCHAR(255) NULL DEFAULT NULL ,
  text16 VARCHAR(255) NULL DEFAULT NULL ,
  text17 VARCHAR(255) NULL DEFAULT NULL ,
  text18 VARCHAR(255) NULL DEFAULT NULL ,
  text19 VARCHAR(255) NULL DEFAULT NULL ,
  text20 VARCHAR(255) NULL DEFAULT NULL ,
  text21 VARCHAR(255) NULL DEFAULT NULL ,
  text22 VARCHAR(255) NULL DEFAULT NULL ,
  text23 VARCHAR(255) NULL DEFAULT NULL ,
  text24 VARCHAR(255) NULL DEFAULT NULL ,
  text25 VARCHAR(255) NULL DEFAULT NULL ,
  text26 VARCHAR(255) NULL DEFAULT NULL ,
  text27 VARCHAR(255) NULL DEFAULT NULL ,
  text28 VARCHAR(255) NULL DEFAULT NULL ,
  text29 VARCHAR(255) NULL DEFAULT NULL ,
  text30 VARCHAR(255) NULL DEFAULT NULL ,
  longtext2 TEXT NULL DEFAULT NULL ,
  longtext3 TEXT NULL DEFAULT NULL ,
  longtext4 TEXT NULL DEFAULT NULL ,
  longtext5 TEXT NULL DEFAULT NULL ,
  html2 TEXT NULL DEFAULT NULL ,
  html3 TEXT NULL DEFAULT NULL ,
  html4 TEXT NULL DEFAULT NULL ,
  html5 TEXT NULL DEFAULT NULL ,
  numeric2 INT(11) NULL DEFAULT NULL ,
  numeric3 INT(11) NULL DEFAULT NULL ,
  numeric4 INT(11) NULL DEFAULT NULL ,
  numeric5 INT(11) NULL DEFAULT NULL ,
  currency2 FLOAT NULL DEFAULT NULL ,
  currency3 FLOAT NULL DEFAULT NULL ,
  currency4 FLOAT NULL DEFAULT NULL ,
  currency5 FLOAT NULL DEFAULT NULL ,
  datetime2 DATETIME NULL DEFAULT NULL ,
  datetime3 DATETIME NULL DEFAULT NULL ,
  datetime4 DATETIME NULL DEFAULT NULL ,
  datetime5 DATETIME NULL DEFAULT NULL ,
  yesno2 BIT(1) NULL DEFAULT NULL ,
  yesno3 BIT(1) NULL DEFAULT NULL ,
  yesno4 BIT(1) NULL DEFAULT NULL ,
  yesno5 BIT(1) NULL DEFAULT NULL ,
  file2 VARCHAR(1000) NULL DEFAULT NULL ,
  file3 VARCHAR(1000) NULL DEFAULT NULL ,
  file4 VARCHAR(1000) NULL DEFAULT NULL ,
  file5 VARCHAR(1000) NULL DEFAULT NULL ,
  OrderNumber INT(11) NULL DEFAULT NULL ,
  LastPublishedFileName VARCHAR(500) NULL DEFAULT NULL ,
  MetaKeywords VARCHAR(500) NULL DEFAULT NULL ,
  MetaDescription VARCHAR(500) NULL DEFAULT NULL ,
  PRIMARY KEY (ID) ,
  UNIQUE INDEX groupUnique (FK_Parent_Group ASC, Name ASC) ,
  INDEX FK_Site (FK_Site ASC) ,
  INDEX FK_Module (FK_DataCollection ASC) ,
  INDEX FK_Group (FK_Parent_Group ASC) ,
  INDEX item_fk_datacollection_index (FK_DataCollection ASC) ,
  INDEX dataitem_fk_parent_group (FK_Parent_Group ASC) ,
  INDEX FK_1 (FK_1 ASC) ,
  INDEX FK_2 (FK_2 ASC) ,
  INDEX FK_3 (FK_3 ASC) ,
  INDEX FK_4 (FK_4 ASC) ,
  INDEX FK_5 (FK_5 ASC) ,
  INDEX FK_6 (FK_6 ASC) ,
  INDEX FK_7 (FK_7 ASC) ,
  INDEX FK_8 (FK_8 ASC) ,
  INDEX FK_9 (FK_9 ASC) ,
  INDEX FK_10 (FK_10 ASC) )
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table dataitemlanguage
-- -----------------------------------------------------
CREATE  TABLE IF NOT EXISTS dataitemlanguage (
  ID VARCHAR(36) NOT NULL ,
  Name VARCHAR(150) NULL DEFAULT NULL ,
  CreateDate DATETIME NULL DEFAULT NULL ,
  ModifiedDate DATETIME NULL DEFAULT NULL ,
  DateFrom DATETIME NULL DEFAULT NULL ,
  DateTill DATETIME NULL DEFAULT NULL ,
  FK_Site VARCHAR(36) NULL DEFAULT NULL ,
  FK_DataCollection VARCHAR(36) NULL DEFAULT NULL ,
  FK_DataItem VARCHAR(36) NULL DEFAULT NULL ,
  LanguageCode VARCHAR(5) NULL DEFAULT NULL ,
  Title VARCHAR(250) NULL DEFAULT NULL ,
  Active INT(11) NULL DEFAULT NULL ,
  ChangeStatus INT(11) NULL DEFAULT NULL ,
  LastPublishedDate DATETIME NULL DEFAULT NULL ,
  LastPublishedFileName VARCHAR(500) NULL DEFAULT NULL ,
  Text1 VARCHAR(255) NULL DEFAULT NULL ,
  Text2 VARCHAR(255) NULL DEFAULT NULL ,
  Text3 VARCHAR(255) NULL DEFAULT NULL ,
  Text4 VARCHAR(255) NULL DEFAULT NULL ,
  Text5 VARCHAR(255) NULL DEFAULT NULL ,
  LongText1 TEXT NULL DEFAULT NULL ,
  Html1 TEXT NULL DEFAULT NULL ,
  Image1 VARCHAR(255) NULL DEFAULT NULL ,
  Image2 VARCHAR(255) NULL DEFAULT NULL ,
  Image3 VARCHAR(255) NULL DEFAULT NULL ,
  Image4 VARCHAR(255) NULL DEFAULT NULL ,
  Image5 VARCHAR(255) NULL DEFAULT NULL ,
  File1 VARCHAR(255) NULL DEFAULT NULL ,
  FK_1 VARCHAR(36) NULL DEFAULT NULL ,
  FK_2 VARCHAR(36) NULL DEFAULT NULL ,
  FK_3 VARCHAR(36) NULL DEFAULT NULL ,
  FK_4 VARCHAR(36) NULL DEFAULT NULL ,
  FK_5 VARCHAR(36) NULL DEFAULT NULL ,
  FK_6 VARCHAR(36) NULL DEFAULT NULL ,
  FK_7 VARCHAR(36) NULL DEFAULT NULL ,
  FK_8 VARCHAR(36) NULL DEFAULT NULL ,
  FK_9 VARCHAR(36) NULL DEFAULT NULL ,
  FK_10 VARCHAR(36) NULL DEFAULT NULL ,
  HasAutorisation BIT(1) NULL DEFAULT NULL ,
  text6 VARCHAR(255) NULL DEFAULT NULL ,
  text7 VARCHAR(255) NULL DEFAULT NULL ,
  text8 VARCHAR(255) NULL DEFAULT NULL ,
  text9 VARCHAR(255) NULL DEFAULT NULL ,
  text10 VARCHAR(255) NULL DEFAULT NULL ,
  text11 VARCHAR(255) NULL DEFAULT NULL ,
  text12 VARCHAR(255) NULL DEFAULT NULL ,
  text13 VARCHAR(255) NULL DEFAULT NULL ,
  text14 VARCHAR(255) NULL DEFAULT NULL ,
  text15 VARCHAR(255) NULL DEFAULT NULL ,
  text16 VARCHAR(255) NULL DEFAULT NULL ,
  text17 VARCHAR(255) NULL DEFAULT NULL ,
  text18 VARCHAR(255) NULL DEFAULT NULL ,
  text19 VARCHAR(255) NULL DEFAULT NULL ,
  text20 VARCHAR(255) NULL DEFAULT NULL ,
  text21 VARCHAR(255) NULL DEFAULT NULL ,
  text22 VARCHAR(255) NULL DEFAULT NULL ,
  text23 VARCHAR(255) NULL DEFAULT NULL ,
  text24 VARCHAR(255) NULL DEFAULT NULL ,
  text25 VARCHAR(255) NULL DEFAULT NULL ,
  text26 VARCHAR(255) NULL DEFAULT NULL ,
  text27 VARCHAR(255) NULL DEFAULT NULL ,
  text28 VARCHAR(255) NULL DEFAULT NULL ,
  text29 VARCHAR(255) NULL DEFAULT NULL ,
  text30 VARCHAR(255) NULL DEFAULT NULL ,
  longtext2 TEXT NULL DEFAULT NULL ,
  longtext3 TEXT NULL DEFAULT NULL ,
  longtext4 TEXT NULL DEFAULT NULL ,
  longtext5 TEXT NULL DEFAULT NULL ,
  html2 TEXT NULL DEFAULT NULL ,
  html3 TEXT NULL DEFAULT NULL ,
  html4 TEXT NULL DEFAULT NULL ,
  html5 TEXT NULL DEFAULT NULL ,
  file2 VARCHAR(1000) NULL DEFAULT NULL ,
  file3 VARCHAR(1000) NULL DEFAULT NULL ,
  file4 VARCHAR(1000) NULL DEFAULT NULL ,
  file5 VARCHAR(1000) NULL DEFAULT NULL ,
  MetaKeywords VARCHAR(500) NULL DEFAULT NULL ,
  MetaDescription VARCHAR(500) NULL DEFAULT NULL ,
  PRIMARY KEY (ID) ,
  INDEX FK_Site (FK_Site ASC) ,
  INDEX FK_DataCollection (FK_DataCollection ASC) ,
  INDEX FK_DataItem (FK_DataItem ASC) ,
  INDEX DataItem_LanguageCode (LanguageCode ASC) )
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table datalookupvalue
-- -----------------------------------------------------
CREATE  TABLE IF NOT EXISTS datalookupvalue (
  ID VARCHAR(36) NOT NULL ,
  Name VARCHAR(50) NULL DEFAULT NULL ,
  CreateDate DATETIME NULL DEFAULT NULL ,
  ModifiedDate DATETIME NULL DEFAULT NULL ,
  DateFrom DATETIME NULL DEFAULT NULL ,
  DateTill DATETIME NULL DEFAULT NULL ,
  Active INT(11) NULL DEFAULT NULL ,
  FK_Site VARCHAR(36) NULL DEFAULT NULL ,
  FK_DataCollection VARCHAR(36) NULL DEFAULT NULL ,
  FK_DataField VARCHAR(36) NULL DEFAULT NULL ,
  IsMultiLanguage BIT(1) NULL DEFAULT NULL ,
  OrderingNumber INT(11) NULL DEFAULT NULL ,
  NL VARCHAR(50) NULL DEFAULT NULL ,
  EN VARCHAR(50) NULL DEFAULT NULL ,
  DE VARCHAR(50) NULL DEFAULT NULL ,
  FR VARCHAR(50) NULL DEFAULT NULL ,
  SP VARCHAR(50) NULL DEFAULT NULL ,
  PL VARCHAR(50) NULL DEFAULT NULL ,
  IT VARCHAR(50) NULL DEFAULT NULL ,
  PRIMARY KEY (ID) ,
  UNIQUE INDEX datalookupvalueNameUnique (Name ASC, FK_DataField ASC) ,
  INDEX FK_Site_Index (FK_Site ASC) ,
  INDEX FK_DataCollection_Index (FK_DataCollection ASC) ,
  INDEX FK_DataField_Index (FK_DataField ASC) )
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table datalookupvalueperitem
-- -----------------------------------------------------
CREATE  TABLE IF NOT EXISTS datalookupvalueperitem (
  ID VARCHAR(36) NOT NULL ,
  Name VARCHAR(50) NULL DEFAULT NULL ,
  CreateDate DATETIME NULL DEFAULT NULL ,
  ModifiedDate DATETIME NULL DEFAULT NULL ,
  DateFrom DATETIME NULL DEFAULT NULL ,
  DateTill DATETIME NULL DEFAULT NULL ,
  FK_Item VARCHAR(36) NOT NULL ,
  FK_LookupValue VARCHAR(36) NOT NULL ,
  Active INT(11) NULL DEFAULT NULL ,
  DataFieldNumber INT(11) NOT NULL DEFAULT '1' ,
  PRIMARY KEY (ID) ,
  INDEX FK_Template_Index (FK_Item ASC) ,
  INDEX FK_Script_Index (FK_LookupValue ASC) ,
  INDEX FK_LookupValue (FK_LookupValue ASC) ,
  INDEX FK_Item (FK_Item ASC) )
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table eventlog
-- -----------------------------------------------------
CREATE  TABLE IF NOT EXISTS eventlog (
  ID VARCHAR(36) NOT NULL ,
  Date DATETIME NOT NULL ,
  Description VARCHAR(2000) NULL DEFAULT NULL ,
  Type VARCHAR(50) NULL DEFAULT NULL ,
  FK_User VARCHAR(36) NULL DEFAULT NULL ,
  FK_Site VARCHAR(36) NULL DEFAULT NULL ,
  Failure BIT(1) NULL DEFAULT NULL ,
  username VARCHAR(50) CHARACTER SET 'utf8' NULL DEFAULT NULL ,
  Name VARCHAR(50) NULL DEFAULT NULL ,
  CreateDate DATETIME NULL DEFAULT NULL ,
  ModifiedDate DATETIME NULL DEFAULT NULL ,
  Active INT(11) NULL DEFAULT NULL ,
  PRIMARY KEY (ID) ,
  INDEX FK_User_Index (FK_User ASC) ,
  INDEX FK_Site_Index (FK_Site ASC) ,
  INDEX Type_Index (Type ASC) ,
  INDEX Date (Date ASC) )
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table language
-- -----------------------------------------------------
CREATE  TABLE IF NOT EXISTS language (
  ID VARCHAR(36) NOT NULL ,
  Name VARCHAR(50) NULL DEFAULT NULL ,
  CreateDate DATETIME NULL DEFAULT NULL ,
  ModifiedDate DATETIME NULL DEFAULT NULL ,
  DateFrom DATETIME NULL DEFAULT NULL ,
  DateTill DATETIME NULL DEFAULT NULL ,
  FK_Site VARCHAR(36) NULL DEFAULT NULL ,
  Code VARCHAR(10) NULL DEFAULT NULL ,
  Active INT(11) NULL DEFAULT NULL ,
  PRIMARY KEY (ID) ,
  UNIQUE INDEX languageNameUNIQUE (Name ASC, FK_Site ASC) ,
  INDEX FK_Site (FK_Site ASC) ,
  INDEX language_LanguageCode (Code ASC) )
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table site
-- -----------------------------------------------------
CREATE  TABLE IF NOT EXISTS site (
  ID VARCHAR(36) NOT NULL ,
  Name VARCHAR(50) NULL DEFAULT NULL ,
  CreateDate DATETIME NULL DEFAULT NULL ,
  ModifiedDate DATETIME NULL DEFAULT NULL ,
  DateFrom DATETIME NULL DEFAULT NULL ,
  DateTill DATETIME NULL DEFAULT NULL ,
  MetaKeywords VARCHAR(255) NULL DEFAULT NULL ,
  MetaDescription VARCHAR(255) NULL DEFAULT NULL ,
  UseGoogleAnalystics BIT(1) NULL DEFAULT NULL ,
  GoogleAnalysticsCode VARCHAR(50) CHARACTER SET 'utf8' NULL DEFAULT NULL ,
  EmailSettingsFrom VARCHAR(100) CHARACTER SET 'utf8' NULL DEFAULT NULL ,
  HeadContent TEXT NULL DEFAULT NULL ,
  LicenceCode VARCHAR(100) NULL DEFAULT NULL ,
  DefaultLanguage VARCHAR(50) NULL DEFAULT NULL ,
  MaxWidthImages INT(11) NULL DEFAULT NULL ,
  MaxWidthThumbnails INT(11) NULL DEFAULT NULL ,
  UseSearchModule BIT(1) NULL DEFAULT NULL ,
  NewUserEmailSubject VARCHAR(250) NULL DEFAULT NULL ,
  NewUserEmailText TEXT NULL DEFAULT NULL ,
  SiteAdminEmail VARCHAR(100) NULL DEFAULT NULL ,
  GoogleMapsKey VARCHAR(100) NULL DEFAULT NULL ,
  Active INT(11) NULL DEFAULT NULL ,
  NewsletterSender VARCHAR(255) NULL DEFAULT NULL ,
  FK_NewsletterOptInEmailPage VARCHAR(36) NULL DEFAULT NULL ,
  NewsletterOptInEmailSubject VARCHAR(255) NULL DEFAULT NULL ,
  EmailSettingsPassword TEXT NULL DEFAULT NULL ,
  FK_NewsletterOptOutEmailPage VARCHAR(36) NULL DEFAULT NULL ,
  NewsletterOptOutEmailSubject VARCHAR(255) NULL DEFAULT NULL ,
  NewsletterOptOutEmailContent TEXT NULL DEFAULT NULL ,
  PRIMARY KEY (ID) ,
  INDEX FK_NewsletterOptInEmailPage (FK_NewsletterOptInEmailPage ASC, FK_NewsletterOptOutEmailPage ASC) ,
  INDEX FK_NewsletterOptOutEmailPage (FK_NewsletterOptOutEmailPage ASC) )
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table menu
-- -----------------------------------------------------
CREATE  TABLE IF NOT EXISTS menu (
  ID VARCHAR(36) NOT NULL ,
  Name VARCHAR(150) NULL DEFAULT NULL ,
  CreateDate DATETIME NULL DEFAULT NULL ,
  ModifiedDate DATETIME NULL DEFAULT NULL ,
  DateFrom DATETIME NULL DEFAULT NULL ,
  DateTill DATETIME NULL DEFAULT NULL ,
  FK_Site VARCHAR(36) NULL DEFAULT NULL ,
  Active INT(11) NULL DEFAULT NULL ,
  ChangeStatus INT(11) NULL DEFAULT NULL ,
  LastPublishedDate DATETIME NULL DEFAULT NULL ,
  LastPublishedFileName VARCHAR(500) NULL DEFAULT NULL ,
  LanguageCode VARCHAR(5) NULL DEFAULT NULL ,
  Type INT(11) NULL DEFAULT NULL ,
  PRIMARY KEY (ID) ,
  INDEX FK_Site (FK_Site ASC) ,
  INDEX Menu_LanguageCode (LanguageCode ASC) ,
  CONSTRAINT menu_fk_site
    FOREIGN KEY (FK_Site )
    REFERENCES site (ID ),
  CONSTRAINT menu_LanguageCode_fk
    FOREIGN KEY (LanguageCode )
    REFERENCES language (Code ))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table page
-- -----------------------------------------------------
CREATE  TABLE IF NOT EXISTS page (
  ID VARCHAR(36) NOT NULL ,
  Name VARCHAR(50) NULL DEFAULT NULL ,
  CreateDate DATETIME NULL DEFAULT NULL ,
  ModifiedDate DATETIME NULL DEFAULT NULL ,
  ContentChangedDate DATETIME NULL DEFAULT NULL ,
  DateFrom DATETIME NULL DEFAULT NULL ,
  DateTill DATETIME NULL DEFAULT NULL ,
  FK_Site VARCHAR(36) NOT NULL ,
  Version INT(11) NULL DEFAULT NULL ,
  FK_Layout VARCHAR(36) NOT NULL ,
  Title VARCHAR(250) NULL DEFAULT NULL ,
  HeadContent TEXT NULL DEFAULT NULL ,
  MetaKeywords VARCHAR(1000) NULL DEFAULT NULL ,
  MetaDescription VARCHAR(255) NULL DEFAULT NULL ,
  MetaRobots VARCHAR(50) NULL DEFAULT NULL ,
  InSiteMap BIT(1) NULL DEFAULT NULL ,
  DisallowRobots BIT(1) NULL DEFAULT NULL ,
  SiteMapChangeFreq VARCHAR(50) NULL DEFAULT NULL ,
  SiteMapPriority FLOAT NULL DEFAULT NULL ,
  FK_Folder VARCHAR(36) NULL DEFAULT NULL ,
  IsHomePage BIT(1) NULL DEFAULT NULL ,
  ChangeStatus INT(11) NULL DEFAULT NULL ,
  LastPublishedDate DATETIME NULL DEFAULT NULL ,
  Active INT(11) NULL DEFAULT NULL ,
  HasAutorisation BIT(1) NULL DEFAULT NULL ,
  LanguageCode VARCHAR(5) NULL DEFAULT NULL ,
  RelativeUrl VARCHAR(250) NULL DEFAULT NULL ,
  bodytagcontent VARCHAR(255) NULL DEFAULT NULL ,
  PRIMARY KEY (ID) ,
  UNIQUE INDEX PageNameUnique (Name ASC, FK_Site ASC, FK_Folder ASC) ,
  UNIQUE INDEX RelativeUrl_Unique (RelativeUrl ASC, FK_Site ASC) ,
  INDEX FK_Site_Index (FK_Site ASC) ,
  INDEX FK_Layout_Index (FK_Layout ASC) ,
  INDEX FK_Folder_Index (FK_Folder ASC) ,
  INDEX page_fk_folder (FK_Folder ASC) ,
  INDEX RelativeUrl_Index (RelativeUrl ASC) )
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table menuitem
-- -----------------------------------------------------
CREATE  TABLE IF NOT EXISTS menuitem (
  ID VARCHAR(36) NOT NULL ,
  Name VARCHAR(150) NULL DEFAULT NULL ,
  CreateDate DATETIME NULL DEFAULT NULL ,
  ModifiedDate DATETIME NULL DEFAULT NULL ,
  DateFrom DATETIME NULL DEFAULT NULL ,
  DateTill DATETIME NULL DEFAULT NULL ,
  FK_Site VARCHAR(36) NULL DEFAULT NULL ,
  Active INT(11) NULL DEFAULT NULL ,
  FK_Menu VARCHAR(36) NULL DEFAULT NULL ,
  FK_Page VARCHAR(36) NULL DEFAULT NULL ,
  Title VARCHAR(150) NULL DEFAULT NULL ,
  OrderingNumber INT(11) NOT NULL DEFAULT '0' ,
  FK_Parent_MenuItem VARCHAR(36) NULL DEFAULT NULL ,
  Target VARCHAR(25) NULL DEFAULT NULL ,
  ExternalUrl VARCHAR(250) NULL DEFAULT NULL ,
  ImageUrl VARCHAR(250) NULL DEFAULT NULL ,
  ImageHoverUrl VARCHAR(250) NULL DEFAULT NULL ,
  ImageActiveUrl VARCHAR(250) NULL DEFAULT NULL ,
  CompletePath VARCHAR(500) NULL DEFAULT NULL ,
  UrlType INT(11) NULL DEFAULT NULL ,
  PRIMARY KEY (ID) ,
  INDEX FK_Site (FK_Site ASC) ,
  INDEX FK_Menu (FK_Menu ASC) ,
  INDEX FK_Page (FK_Page ASC) ,
  INDEX FK_Parent_MenuItem (FK_Parent_MenuItem ASC) ,
  CONSTRAINT menuitem_fk_parent
    FOREIGN KEY (FK_Parent_MenuItem )
    REFERENCES menuitem (ID )
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT menuitem_fk_menu
    FOREIGN KEY (FK_Menu )
    REFERENCES menu (ID )
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT menuitem_fk_page
    FOREIGN KEY (FK_Page )
    REFERENCES page (ID )
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT menuitem_fk_site
    FOREIGN KEY (FK_Site )
    REFERENCES site (ID )
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table module
-- -----------------------------------------------------
CREATE  TABLE IF NOT EXISTS module (
  ID VARCHAR(36) NOT NULL ,
  Name VARCHAR(50) NULL DEFAULT NULL ,
  CreateDate DATETIME NULL DEFAULT NULL ,
  ModifiedDate DATETIME NULL DEFAULT NULL ,
  DateFrom DATETIME NULL DEFAULT NULL ,
  DateTill DATETIME NULL DEFAULT NULL ,
  FK_Site VARCHAR(36) NULL DEFAULT NULL ,
  FK_Page VARCHAR(36) NULL DEFAULT NULL ,
  Content TEXT NULL DEFAULT NULL ,
  OrderingNumber INT(11) NULL DEFAULT NULL ,
  Type VARCHAR(100) NULL DEFAULT NULL ,
  FK_Template VARCHAR(36) NULL DEFAULT NULL ,
  FK_DataCollection VARCHAR(36) NULL DEFAULT NULL ,
  FK_Newsletter VARCHAR(36) NULL DEFAULT NULL ,
  ShowInactive BIT(1) NULL DEFAULT NULL ,
  Active INT(11) NULL DEFAULT NULL ,
  Settings VARCHAR(2000) NULL DEFAULT NULL ,
  HasAutorisation BIT(1) NULL DEFAULT NULL ,
  ChangeStatus INT(11) NULL DEFAULT NULL ,
  LastPublishedDate DATETIME NULL DEFAULT NULL ,
  ContainerName VARCHAR(50) NULL DEFAULT NULL ,
  PrePublishedContent LONGTEXT NULL DEFAULT NULL ,
  VisibleMode INT(11) NOT NULL DEFAULT '0' ,
  PRIMARY KEY (ID) ,
  INDEX FK_Site_Index (FK_Site ASC) ,
  INDEX FK_Page_Index (FK_Page ASC) ,
  INDEX FK_Newsletter_Index (FK_Newsletter ASC) )
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table modulenavigationaction
-- -----------------------------------------------------
CREATE  TABLE IF NOT EXISTS modulenavigationaction (
  ID VARCHAR(36) NOT NULL ,
  Name VARCHAR(150) NULL DEFAULT NULL ,
  CreateDate DATETIME NULL DEFAULT NULL ,
  ModifiedDate DATETIME NULL DEFAULT NULL ,
  DateFrom DATETIME NULL DEFAULT NULL ,
  DateTill DATETIME NULL DEFAULT NULL ,
  FK_Site VARCHAR(36) NULL DEFAULT NULL ,
  FK_Module VARCHAR(36) NULL DEFAULT NULL ,
  Active INT(11) NULL DEFAULT NULL ,
  NavigationType INT(11) NULL DEFAULT NULL ,
  FK_NavigationPage VARCHAR(36) NULL DEFAULT NULL ,
  JsFunction VARCHAR(500) NULL DEFAULT NULL ,
  RefreshModules VARCHAR(500) NULL DEFAULT NULL ,
  PRIMARY KEY (ID) ,
  INDEX FK_Site_Index (FK_Site ASC) ,
  INDEX FK_Module_Index (FK_Module ASC) ,
  INDEX FK_NavigationPage_Index (FK_NavigationPage ASC) )
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table moduleperpage
-- -----------------------------------------------------
CREATE  TABLE IF NOT EXISTS moduleperpage (
  ID VARCHAR(36) NOT NULL ,
  FK_Module VARCHAR(36) NOT NULL ,
  FK_Page VARCHAR(36) NOT NULL ,
  PRIMARY KEY (FK_Module, FK_Page) ,
  INDEX FK_Page (FK_Page ASC) )
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table newsletter
-- -----------------------------------------------------
CREATE  TABLE IF NOT EXISTS newsletter (
  ID VARCHAR(36) NOT NULL ,
  Name VARCHAR(50) NULL DEFAULT NULL ,
  CreateDate DATETIME NULL DEFAULT NULL ,
  ModifiedDate DATETIME NULL DEFAULT NULL ,
  ContentChangedDate DATETIME NULL DEFAULT NULL ,
  DateFrom DATETIME NULL DEFAULT NULL ,
  DateTill DATETIME NULL DEFAULT NULL ,
  FK_Site VARCHAR(36) NOT NULL ,
  Version INT(11) NULL DEFAULT NULL ,
  FK_Layout VARCHAR(36) NOT NULL ,
  Path VARCHAR(150) NULL DEFAULT NULL ,
  Title VARCHAR(250) NULL DEFAULT NULL ,
  InMenu BIT(1) NULL DEFAULT NULL ,
  MenuText VARCHAR(50) NULL DEFAULT NULL ,
  MenuIconUrl VARCHAR(100) NULL DEFAULT NULL ,
  MenuBackgroundImageUrl VARCHAR(100) NULL DEFAULT NULL ,
  FK_Parent_Page VARCHAR(36) NULL DEFAULT NULL ,
  HeadContent TEXT NULL DEFAULT NULL ,
  MetaKeywords VARCHAR(1000) NULL DEFAULT NULL ,
  MetaDescription VARCHAR(255) NULL DEFAULT NULL ,
  MetaRobots VARCHAR(50) NULL DEFAULT NULL ,
  InSiteMap BIT(1) NULL DEFAULT NULL ,
  DisallowRobots BIT(1) NULL DEFAULT NULL ,
  SiteMapChangeFreq VARCHAR(50) NULL DEFAULT NULL ,
  SiteMapPriority FLOAT NULL DEFAULT NULL ,
  BodyTagContent VARCHAR(250) NULL DEFAULT NULL ,
  FK_Folder VARCHAR(36) NULL DEFAULT NULL ,
  IsHomePage BIT(1) NULL DEFAULT NULL ,
  ChangeStatus INT(11) NULL DEFAULT NULL ,
  LastPublishedDate DATETIME NULL DEFAULT NULL ,
  Active INT(11) NULL DEFAULT NULL ,
  FK_LiveObject VARCHAR(36) NULL DEFAULT NULL ,
  FK_WorkingObject VARCHAR(36) NULL DEFAULT NULL ,
  LastPublishedFileName VARCHAR(500) NULL DEFAULT NULL ,
  HasAutorisation BIT(1) NULL DEFAULT NULL ,
  LanguageCode VARCHAR(5) NULL DEFAULT NULL ,
  RelativeUrl VARCHAR(250) NULL DEFAULT NULL ,
  ExpirationDate DATETIME NULL DEFAULT NULL ,
  IsSent TINYINT(1) NULL DEFAULT NULL ,
  SendNewsletterAfterRegistration TINYINT(1) NULL DEFAULT NULL ,
  SendDate DATETIME NULL DEFAULT NULL ,
  SentFromAddress VARCHAR(200) NULL DEFAULT NULL ,
  Subject VARCHAR(255) NULL DEFAULT NULL ,
  UNIQUE INDEX ID (ID ASC) ,
  UNIQUE INDEX RelativeUrl_Unique (RelativeUrl ASC, FK_Site ASC) ,
  INDEX FK_Layout (FK_Layout ASC) ,
  INDEX FK_Site (FK_Site ASC) ,
  INDEX RelativeUrl_Index (RelativeUrl ASC) )
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table newslettergroup
-- -----------------------------------------------------
CREATE  TABLE IF NOT EXISTS newslettergroup (
  ID VARCHAR(36) NOT NULL ,
  Name VARCHAR(150) NULL DEFAULT NULL ,
  CreateDate DATETIME NULL DEFAULT NULL ,
  ModifiedDate DATETIME NULL DEFAULT NULL ,
  DateFrom DATETIME NULL DEFAULT NULL ,
  DateTill DATETIME NULL DEFAULT NULL ,
  FK_Site VARCHAR(36) NULL DEFAULT NULL ,
  Active INT(11) NULL DEFAULT NULL ,
  ChangeStatus INT(11) NULL DEFAULT NULL ,
  LastPublishedDate DATETIME NULL DEFAULT NULL ,
  LastPublishedFileName VARCHAR(500) NULL DEFAULT NULL ,
  HasAutorisation BIT(1) NULL DEFAULT NULL ,
  IsChoosableGroup TINYINT(1) NOT NULL ,
  IsMandatoryGroup TINYINT(1) NULL DEFAULT NULL ,
  PRIMARY KEY (ID) ,
  UNIQUE INDEX NameUnique (Name ASC) ,
  INDEX FK_Site (FK_Site ASC) )
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table newslettergroupsubscriber
-- -----------------------------------------------------
CREATE  TABLE IF NOT EXISTS newslettergroupsubscriber (
  ID VARCHAR(36) NOT NULL ,
  Name VARCHAR(150) NULL DEFAULT NULL ,
  CreateDate DATETIME NULL DEFAULT NULL ,
  ModifiedDate DATETIME NULL DEFAULT NULL ,
  DateFrom DATETIME NULL DEFAULT NULL ,
  DateTill DATETIME NULL DEFAULT NULL ,
  FK_Site VARCHAR(36) NULL DEFAULT NULL ,
  Active INT(11) NULL DEFAULT NULL ,
  ChangeStatus INT(11) NULL DEFAULT NULL ,
  LastPublishedDate DATETIME NULL DEFAULT NULL ,
  LastPublishedFileName VARCHAR(500) NULL DEFAULT NULL ,
  FK_NewsletterSubscriber VARCHAR(36) NOT NULL ,
  FK_NewsletterGroup VARCHAR(36) NOT NULL ,
  PRIMARY KEY (FK_NewsletterSubscriber, FK_NewsletterGroup) ,
  INDEX FK_NewsletterGroup (FK_NewsletterGroup ASC) )
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table newsletterlayout
-- -----------------------------------------------------
CREATE  TABLE IF NOT EXISTS newsletterlayout (
  ID VARCHAR(36) NOT NULL ,
  Name VARCHAR(50) NULL DEFAULT NULL ,
  CreateDate DATETIME NULL DEFAULT NULL ,
  ModifiedDate DATETIME NULL DEFAULT NULL ,
  DateFrom DATETIME NULL DEFAULT NULL ,
  DateTill DATETIME NULL DEFAULT NULL ,
  FK_Site VARCHAR(36) NULL DEFAULT NULL ,
  FK_ModuleLayout VARCHAR(36) NULL DEFAULT NULL ,
  Content TEXT NULL DEFAULT NULL ,
  CssStyle TEXT NULL DEFAULT NULL ,
  CssMenuStyle TEXT NULL DEFAULT NULL ,
  DefaultSubject VARCHAR(100) NULL DEFAULT NULL ,
  DefaultSentToQuery VARCHAR(1000) NULL DEFAULT NULL ,
  HeadContent VARCHAR(250) CHARACTER SET 'utf8' NULL DEFAULT NULL ,
  Language VARCHAR(100) CHARACTER SET 'utf8' NULL DEFAULT NULL ,
  BodyTagContent VARCHAR(100) CHARACTER SET 'utf8' NULL DEFAULT NULL ,
  Active INT(11) NULL DEFAULT NULL ,
  PRIMARY KEY (ID) ,
  INDEX FK_Site_Index (FK_Site ASC) ,
  INDEX FK_FK_ModuleLayout_Index (FK_ModuleLayout ASC) )
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table newsletterlayoutcontainer
-- -----------------------------------------------------
CREATE  TABLE IF NOT EXISTS newsletterlayoutcontainer (
  ID VARCHAR(36) NOT NULL ,
  Name VARCHAR(50) NULL DEFAULT NULL ,
  CreateDate DATETIME NULL DEFAULT NULL ,
  ModifiedDate DATETIME NULL DEFAULT NULL ,
  DateFrom DATETIME NULL DEFAULT NULL ,
  DateTill DATETIME NULL DEFAULT NULL ,
  Content TEXT NULL DEFAULT NULL ,
  FK_NewsletterLayout VARCHAR(36) NULL DEFAULT NULL ,
  FK_Layout VARCHAR(36) NULL DEFAULT NULL ,
  FK_Site VARCHAR(36) NULL DEFAULT NULL ,
  Active INT(11) NULL DEFAULT NULL ,
  PRIMARY KEY (ID) ,
  INDEX FK_Layout_Index (FK_NewsletterLayout ASC) ,
  INDEX FK_Site_index (FK_Site ASC) )
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table newslettermailing
-- -----------------------------------------------------
CREATE  TABLE IF NOT EXISTS newslettermailing (
  ID VARCHAR(36) NOT NULL ,
  Name VARCHAR(150) NULL DEFAULT NULL ,
  CreateDate DATETIME NULL DEFAULT NULL ,
  ModifiedDate DATETIME NULL DEFAULT NULL ,
  DateFrom DATETIME NULL DEFAULT NULL ,
  DateTill DATETIME NULL DEFAULT NULL ,
  FK_Site VARCHAR(36) NULL DEFAULT NULL ,
  Title VARCHAR(250) NULL DEFAULT NULL ,
  Active INT(11) NULL DEFAULT NULL ,
  ChangeStatus INT(11) NULL DEFAULT NULL ,
  LastPublishedDate DATETIME NULL DEFAULT NULL ,
  LastPublishedFileName VARCHAR(500) NULL DEFAULT NULL ,
  FK_NewsletterSubscriber VARCHAR(36) NOT NULL ,
  FK_Newsletter VARCHAR(36) NOT NULL ,
  NewsletterSent TINYINT(1) NOT NULL DEFAULT '0' ,
  EmailAddress VARCHAR(255) NULL DEFAULT NULL ,
  INDEX FK_NewsletterSubscriber (FK_NewsletterSubscriber ASC, FK_Newsletter ASC) ,
  INDEX FK_Newsletter (FK_Newsletter ASC) ,
  INDEX ID (ID ASC) )
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table newslettermailingstatistics
-- -----------------------------------------------------
CREATE  TABLE IF NOT EXISTS newslettermailingstatistics (
  ID VARCHAR(36) NOT NULL ,
  Name VARCHAR(50) NULL DEFAULT NULL ,
  CreateDate DATETIME NULL DEFAULT NULL ,
  ModifiedDate DATETIME NULL DEFAULT NULL ,
  DateFrom DATETIME NULL DEFAULT NULL ,
  DateTill DATETIME NULL DEFAULT NULL ,
  FK_Site VARCHAR(36) NULL DEFAULT NULL ,
  FK_Newsletter VARCHAR(36) NULL DEFAULT NULL ,
  FK_Mailing VARCHAR(36) NULL DEFAULT NULL ,
  FK_User VARCHAR(36) NULL DEFAULT NULL ,
  FK_Page VARCHAR(36) NULL DEFAULT NULL ,
  FK_Item VARCHAR(36) NULL DEFAULT NULL ,
  FK_Group VARCHAR(36) NULL DEFAULT NULL ,
  UserEmail VARCHAR(50) NULL DEFAULT NULL ,
  url VARCHAR(1000) NULL DEFAULT NULL ,
  IPAddress VARCHAR(20) NULL DEFAULT NULL ,
  log VARCHAR(500) NULL DEFAULT NULL ,
  Active INT(11) NULL DEFAULT NULL ,
  PRIMARY KEY (ID) ,
  INDEX FK_Site_index (FK_Site ASC) ,
  INDEX FK_Newsletter_index (FK_Newsletter ASC) ,
  INDEX FK_Mailing_index (FK_Mailing ASC) )
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table newsletterpergroup
-- -----------------------------------------------------
CREATE  TABLE IF NOT EXISTS newsletterpergroup (
  ID VARCHAR(36) NOT NULL ,
  Name VARCHAR(150) NULL DEFAULT NULL ,
  CreateDate DATETIME NULL DEFAULT NULL ,
  ModifiedDate DATETIME NULL DEFAULT NULL ,
  DateFrom DATETIME NULL DEFAULT NULL ,
  DateTill DATETIME NULL DEFAULT NULL ,
  FK_Site VARCHAR(36) NULL DEFAULT NULL ,
  Active INT(11) NULL DEFAULT NULL ,
  ChangeStatus INT(11) NULL DEFAULT NULL ,
  LastPublishedDate DATETIME NULL DEFAULT NULL ,
  LastPublishedFileName VARCHAR(500) NULL DEFAULT NULL ,
  FK_Newsletter VARCHAR(36) NOT NULL ,
  FK_NewsletterGroup VARCHAR(36) NOT NULL ,
  PRIMARY KEY (FK_Newsletter, FK_NewsletterGroup) ,
  INDEX FK_NewsletterGroup (FK_NewsletterGroup ASC) )
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table newslettersubscriber
-- -----------------------------------------------------
CREATE  TABLE IF NOT EXISTS newslettersubscriber (
  ID VARCHAR(36) NOT NULL ,
  FK_User VARCHAR(36) NULL DEFAULT NULL ,
  Name VARCHAR(150) NULL DEFAULT NULL ,
  CreateDate DATETIME NULL DEFAULT NULL ,
  ModifiedDate DATETIME NULL DEFAULT NULL ,
  DateFrom DATETIME NULL DEFAULT NULL ,
  DateTill DATETIME NULL DEFAULT NULL ,
  FK_Site VARCHAR(36) NULL DEFAULT NULL ,
  Title VARCHAR(250) NULL DEFAULT NULL ,
  Active INT(11) NULL DEFAULT NULL ,
  Confirmed TINYINT(1) NULL DEFAULT NULL ,
  Unsubscribed TINYINT(1) NULL DEFAULT '0' ,
  UnsubscribeDate DATETIME NULL DEFAULT NULL ,
  Email VARCHAR(50) NULL DEFAULT NULL ,
  ForeName VARCHAR(250) NULL DEFAULT NULL ,
  NamePrefix VARCHAR(25) NULL DEFAULT NULL ,
  CompanyName VARCHAR(150) NULL DEFAULT NULL ,
  Gender INT(11) NULL DEFAULT NULL ,
  PRIMARY KEY (ID) ,
  INDEX FK_USER (FK_User ASC) )
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table pagefolder
-- -----------------------------------------------------
CREATE  TABLE IF NOT EXISTS pagefolder (
  ID VARCHAR(36) NOT NULL ,
  Name VARCHAR(50) NULL DEFAULT NULL ,
  CreateDate DATETIME NULL DEFAULT NULL ,
  ModifiedDate DATETIME NULL DEFAULT NULL ,
  DateFrom DATETIME NULL DEFAULT NULL ,
  DateTill DATETIME NULL DEFAULT NULL ,
  FK_Site VARCHAR(36) NULL DEFAULT NULL ,
  FK_Parent_Folder VARCHAR(36) NULL DEFAULT NULL ,
  RelativePath VARCHAR(255) NULL DEFAULT NULL ,
  Active INT(11) NULL DEFAULT NULL ,
  ChangeStatus INT(11) NULL DEFAULT NULL ,
  LastPublishedDate DATETIME NULL DEFAULT NULL ,
  HasAutorisation BIT(1) NULL DEFAULT NULL ,
  PRIMARY KEY (ID) ,
  UNIQUE INDEX FolderNameUnique (Name ASC, FK_Parent_Folder ASC) ,
  INDEX FK_Site_Index (FK_Site ASC) ,
  INDEX FK_Parent_Folder_Index (FK_Parent_Folder ASC) ,
  INDEX FK_Parent_Folder (FK_Parent_Folder ASC) )
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table script
-- -----------------------------------------------------
CREATE  TABLE IF NOT EXISTS script (
  ID VARCHAR(36) NOT NULL ,
  Name VARCHAR(50) NOT NULL ,
  CreateDate DATETIME NULL DEFAULT NULL ,
  ModifiedDate DATETIME NULL DEFAULT NULL ,
  DateFrom DATETIME NULL DEFAULT NULL ,
  DateTill DATETIME NULL DEFAULT NULL ,
  FK_Site VARCHAR(36) NULL DEFAULT NULL ,
  ScriptType INT(11) NOT NULL ,
  Content LONGTEXT NULL DEFAULT NULL ,
  Active INT(11) NULL DEFAULT NULL ,
  ChangeStatus INT(11) NULL DEFAULT NULL ,
  LastPublishedDate DATETIME NULL DEFAULT NULL ,
  HasAutorisation BIT(1) NULL DEFAULT NULL ,
  ActiveInEditor TINYINT(1) NOT NULL DEFAULT '1' ,
  LoadInWholeSite BIT(1) NULL DEFAULT NULL ,
  StylesheetMedia VARCHAR(50) NULL DEFAULT NULL ,
  IsSystemValue BIT(1) NULL DEFAULT NULL ,
  PRIMARY KEY (ID) ,
  UNIQUE INDEX Script_Name_Unique (Name ASC, ScriptType ASC, FK_Site ASC) ,
  INDEX FK_Site_Index (FK_Site ASC) )
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table scriptpermenu
-- -----------------------------------------------------
CREATE  TABLE IF NOT EXISTS scriptpermenu (
  ID VARCHAR(36) NOT NULL ,
  Name VARCHAR(50) NULL DEFAULT NULL ,
  CreateDate DATETIME NULL DEFAULT NULL ,
  ModifiedDate DATETIME NULL DEFAULT NULL ,
  DateFrom DATETIME NULL DEFAULT NULL ,
  DateTill DATETIME NULL DEFAULT NULL ,
  FK_Menu VARCHAR(36) NOT NULL ,
  FK_Script VARCHAR(36) NOT NULL ,
  Active INT(11) NULL DEFAULT NULL ,
  PRIMARY KEY (ID) ,
  INDEX FK_Menu_Index (FK_Menu ASC) ,
  INDEX FK_Script_Index (FK_Script ASC) ,
  CONSTRAINT ScriptPerMenu_fk_menu
    FOREIGN KEY (FK_Menu )
    REFERENCES menu (ID ),
  CONSTRAINT ScriptPerMenu_fk_script
    FOREIGN KEY (FK_Script )
    REFERENCES script (ID ))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table scriptperpage
-- -----------------------------------------------------
CREATE  TABLE IF NOT EXISTS scriptperpage (
  ID VARCHAR(36) NOT NULL ,
  Name VARCHAR(50) NULL DEFAULT NULL ,
  CreateDate DATETIME NULL DEFAULT NULL ,
  ModifiedDate DATETIME NULL DEFAULT NULL ,
  DateFrom DATETIME NULL DEFAULT NULL ,
  DateTill DATETIME NULL DEFAULT NULL ,
  FK_Page VARCHAR(36) NOT NULL ,
  FK_Script VARCHAR(36) NOT NULL ,
  Active INT(11) NULL DEFAULT NULL ,
  PRIMARY KEY (ID) ,
  INDEX FK_Page_Index (FK_Page ASC) ,
  INDEX FK_Script_Index (FK_Script ASC) )
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table scriptpertemplate
-- -----------------------------------------------------
CREATE  TABLE IF NOT EXISTS scriptpertemplate (
  ID VARCHAR(36) NOT NULL ,
  Name VARCHAR(50) NULL DEFAULT NULL ,
  CreateDate DATETIME NULL DEFAULT NULL ,
  ModifiedDate DATETIME NULL DEFAULT NULL ,
  DateFrom DATETIME NULL DEFAULT NULL ,
  DateTill DATETIME NULL DEFAULT NULL ,
  FK_Template VARCHAR(36) NOT NULL ,
  FK_Script VARCHAR(36) NOT NULL ,
  Active INT(11) NULL DEFAULT NULL ,
  PRIMARY KEY (ID) ,
  INDEX FK_Template_Index (FK_Template ASC) ,
  INDEX FK_Script_Index (FK_Script ASC) )
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table searchindex
-- -----------------------------------------------------
CREATE  TABLE IF NOT EXISTS searchindex (
  ID VARCHAR(36) NOT NULL ,
  Name VARCHAR(250) NULL DEFAULT NULL ,
  CreateDate DATETIME NULL DEFAULT NULL ,
  ModifiedDate DATETIME NULL DEFAULT NULL ,
  DateFrom DATETIME NULL DEFAULT NULL ,
  DateTill DATETIME NULL DEFAULT NULL ,
  FK_Site VARCHAR(36) NULL DEFAULT NULL ,
  FK_Page VARCHAR(36) NULL DEFAULT NULL ,
  Title VARCHAR(250) NULL DEFAULT NULL ,
  url VARCHAR(250) NULL DEFAULT NULL ,
  MetaDescription TEXT NULL DEFAULT NULL ,
  Content TEXT NULL DEFAULT NULL ,
  Type VARCHAR(50) NULL DEFAULT NULL ,
  Active INT(11) NULL DEFAULT NULL ,
  FK_DataCollection VARCHAR(36) NULL DEFAULT NULL ,
  MetaKeywords VARCHAR(250) NULL DEFAULT NULL ,
  PRIMARY KEY (ID) ,
  INDEX FK_Site (FK_Site ASC) ,
  FULLTEXT INDEX Title (Title ASC, url ASC, MetaDescription ASC, Content ASC) ,
  FULLTEXT INDEX Meta (MetaDescription ASC, Content ASC) )
ENGINE = MyISAM
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table siteenvironment
-- -----------------------------------------------------
CREATE  TABLE IF NOT EXISTS siteenvironment (
  ID VARCHAR(36) NOT NULL ,
  Name VARCHAR(150) NULL DEFAULT NULL ,
  CreateDate DATETIME NULL DEFAULT NULL ,
  ModifiedDate DATETIME NULL DEFAULT NULL ,
  DateFrom DATETIME NULL DEFAULT NULL ,
  DateTill DATETIME NULL DEFAULT NULL ,
  FK_Site VARCHAR(36) NULL DEFAULT NULL ,
  Active INT(11) NULL DEFAULT NULL ,
  LastPublishedDate DATETIME NULL DEFAULT NULL ,
  SiteEnvironmentType INT(11) NULL DEFAULT NULL ,
  Path VARCHAR(255) NULL DEFAULT NULL ,
  DomainName VARCHAR(50) NULL DEFAULT NULL ,
  DataBaseName VARCHAR(50) NULL DEFAULT NULL ,
  EmailSettingsHost VARCHAR(50) NULL DEFAULT NULL ,
  EmailSettingsFrom VARCHAR(50) NULL DEFAULT NULL ,
  EmailSettingsUser VARCHAR(50) NULL DEFAULT NULL ,
  EmailSettingsPassword VARCHAR(50) NULL DEFAULT NULL ,
  PRIMARY KEY (ID) ,
  UNIQUE INDEX Environment_Name_Unique (Name ASC, FK_Site ASC) ,
  INDEX FK_Site (FK_Site ASC) )
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table siteuser
-- -----------------------------------------------------
CREATE  TABLE IF NOT EXISTS siteuser (
  ID VARCHAR(36) NOT NULL ,
  Name VARCHAR(50) NULL DEFAULT NULL ,
  CreateDate DATETIME NULL DEFAULT NULL ,
  ModifiedDate DATETIME NULL DEFAULT NULL ,
  DateFrom DATETIME NULL DEFAULT NULL ,
  DateTill DATETIME NULL DEFAULT NULL ,
  FK_Site VARCHAR(36) NULL DEFAULT NULL ,
  Password VARCHAR(100) NULL DEFAULT NULL ,
  Email VARCHAR(50) NULL DEFAULT NULL ,
  Telephone VARCHAR(50) NULL DEFAULT NULL ,
  Gender INT(11) NULL DEFAULT NULL ,
  MessageHeader VARCHAR(50) NULL DEFAULT NULL ,
  BirthDate DATETIME NULL DEFAULT NULL ,
  Address VARCHAR(50) NULL DEFAULT NULL ,
  Postalcode VARCHAR(50) NULL DEFAULT NULL ,
  City VARCHAR(50) NULL DEFAULT NULL ,
  Country VARCHAR(50) NULL DEFAULT NULL ,
  IsSystemValue BIT(1) NULL DEFAULT NULL ,
  IPAddress VARCHAR(20) CHARACTER SET 'utf8' NULL DEFAULT NULL ,
  AllowLogin BIT(1) NULL DEFAULT NULL ,
  EmailIsValid BIT(1) NULL DEFAULT NULL ,
  ReceiveNewsletter BIT(1) NULL DEFAULT NULL ,
  Registration VARCHAR(50) CHARACTER SET 'utf8' NULL DEFAULT NULL ,
  SecretCode VARCHAR(100) CHARACTER SET 'utf8' NULL DEFAULT NULL ,
  CustomerNumber VARCHAR(50) NULL DEFAULT NULL ,
  CompanyName VARCHAR(150) NULL DEFAULT NULL ,
  FaxNumber VARCHAR(50) NULL DEFAULT NULL ,
  AcceptConditions BIT(1) NULL DEFAULT NULL ,
  DateUnsubscribed DATETIME NULL DEFAULT NULL ,
  ForeName VARCHAR(250) NULL DEFAULT NULL ,
  NamePrefix VARCHAR(25) NULL DEFAULT NULL ,
  FormData TEXT NULL DEFAULT NULL ,
  Active INT(11) NULL DEFAULT NULL ,
  PasswordLastChanged DATETIME NULL DEFAULT NULL ,
  PRIMARY KEY (ID) ,
  UNIQUE INDEX EmailPerSiteUnique (Email ASC, FK_Site ASC) ,
  INDEX FK_Site_Index (FK_Site ASC) )
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table siteusergroup
-- -----------------------------------------------------
CREATE  TABLE IF NOT EXISTS siteusergroup (
  ID VARCHAR(36) NOT NULL ,
  Name VARCHAR(50) NULL DEFAULT NULL ,
  CreateDate DATETIME NULL DEFAULT NULL ,
  ModifiedDate DATETIME NULL DEFAULT NULL ,
  DateFrom DATETIME NULL DEFAULT NULL ,
  DateTill DATETIME NULL DEFAULT NULL ,
  FK_Site VARCHAR(36) NULL DEFAULT NULL ,
  Type INT(11) NULL DEFAULT NULL ,
  IsPublicVisible BIT(1) NULL DEFAULT NULL ,
  FK_Parent_Group VARCHAR(36) NULL DEFAULT NULL ,
  Active INT(11) NULL DEFAULT NULL ,
  PRIMARY KEY (ID) ,
  INDEX FK_Site_Index (FK_Site ASC) ,
  INDEX usergroup_parent_group (FK_Parent_Group ASC) )
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table siteusergroupperuser
-- -----------------------------------------------------
CREATE  TABLE IF NOT EXISTS siteusergroupperuser (
  ID VARCHAR(36) NOT NULL ,
  Name VARCHAR(50) NULL DEFAULT NULL ,
  CreateDate DATETIME NULL DEFAULT NULL ,
  ModifiedDate DATETIME NULL DEFAULT NULL ,
  DateFrom DATETIME NULL DEFAULT NULL ,
  DateTill DATETIME NULL DEFAULT NULL ,
  FK_Site VARCHAR(36) NULL DEFAULT NULL ,
  FK_User VARCHAR(36) NULL DEFAULT NULL ,
  FK_UserGroup VARCHAR(36) NULL DEFAULT NULL ,
  Active INT(11) NULL DEFAULT NULL ,
  PRIMARY KEY (ID) ,
  INDEX FK_Site_Index (FK_Site ASC) ,
  INDEX FK_User_Index (FK_User ASC) ,
  INDEX FK_UserGroup_Index (FK_UserGroup ASC) )
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table template
-- -----------------------------------------------------
CREATE  TABLE IF NOT EXISTS template (
  ID VARCHAR(36) NOT NULL ,
  Name VARCHAR(50) NULL DEFAULT NULL ,
  CreateDate DATETIME NULL DEFAULT NULL ,
  ModifiedDate DATETIME NULL DEFAULT NULL ,
  DateFrom DATETIME NULL DEFAULT NULL ,
  DateTill DATETIME NULL DEFAULT NULL ,
  FK_Site VARCHAR(36) NULL DEFAULT NULL ,
  Content TEXT NULL DEFAULT NULL ,
  ChangeStatus INT(11) NULL DEFAULT NULL ,
  Active INT(11) NULL DEFAULT NULL ,
  HasAutorisation BIT(1) NULL DEFAULT NULL ,
  LanguageCode VARCHAR(5) NULL DEFAULT NULL ,
  IsNewsletterTemplate TINYINT(1) NULL DEFAULT NULL ,
  bodytagcontent VARCHAR(255) NULL DEFAULT NULL ,
  PRIMARY KEY (ID) ,
  UNIQUE INDEX Template_Name_Unique (Name ASC, FK_Site ASC) ,
  INDEX FK_Site_Index (FK_Site ASC) ,
  INDEX template_LanguageCode (LanguageCode ASC) )
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table usergroupobjectpermission
-- -----------------------------------------------------
CREATE  TABLE IF NOT EXISTS usergroupobjectpermission (
  ID VARCHAR(36) NOT NULL ,
  Name VARCHAR(50) NULL DEFAULT NULL ,
  CreateDate DATETIME NULL DEFAULT NULL ,
  ModifiedDate DATETIME NULL DEFAULT NULL ,
  Active INT(11) NULL DEFAULT NULL ,
  DateFrom DATETIME NULL DEFAULT NULL ,
  DateTill DATETIME NULL DEFAULT NULL ,
  fk_siteusergroup VARCHAR(36) NULL DEFAULT NULL ,
  FK_Object VARCHAR(36) NOT NULL ,
  ObjectType VARCHAR(50) NULL DEFAULT NULL ,
  PermissionType INT(11) NULL DEFAULT NULL ,
  fk_bitplateusergroup VARCHAR(36) NULL DEFAULT NULL ,
  PRIMARY KEY (ID) ,
  INDEX FK_UserGroup_Index_UserGroupObjectPermission (fk_siteusergroup ASC) ,
  INDEX FK_Object_Index_UserGroupObjectPermission (FK_Object ASC) ,
  INDEX fk_bitplateusergroup (fk_bitplateusergroup ASC) )
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table userobjectpermission
-- -----------------------------------------------------
CREATE  TABLE IF NOT EXISTS userobjectpermission (
  ID VARCHAR(36) NOT NULL ,
  Name VARCHAR(50) NULL DEFAULT NULL ,
  CreateDate DATETIME NULL DEFAULT NULL ,
  ModifiedDate DATETIME NULL DEFAULT NULL ,
  Active INT(11) NULL DEFAULT NULL ,
  DateFrom DATETIME NULL DEFAULT NULL ,
  DateTill DATETIME NULL DEFAULT NULL ,
  fk_siteuser VARCHAR(36) NULL DEFAULT NULL ,
  FK_Object VARCHAR(36) NOT NULL ,
  ObjectType VARCHAR(50) NULL DEFAULT NULL ,
  PermissionType INT(11) NULL DEFAULT NULL ,
  fk_bitplateuser VARCHAR(36) NULL DEFAULT NULL ,
  PRIMARY KEY (ID) ,
  INDEX FK_User_Index_UserObjectPermission (fk_siteuser ASC) ,
  INDEX FK_Object_Index_UserObjectPermission (FK_Object ASC) ,
  INDEX fk_bitplateuser (fk_bitplateuser ASC) )
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;




SET FOREIGN_KEY_CHECKS=1;
SET UNIQUE_CHECKS=1;
